---
title: "Calendar"
---


The calendar below lists the tentative course topics. The dates listed are subject to change at the instructor's discretion.

<!-- As part of the course, there are several articles, papers and technical reports that you will need to read during the semester. Most of the articles themselves are accessible through the [University of Minnesota library website](http://www.lib.umn.edu). In order to access the full text of some of the articles, you will need to log in using your University x500 username and password. More detailed information, including references or links to specific readings, are linked under the day's "Reading". -->

<br /><br />


<br />


<table class="table">

<thead>
<tr>
<th style="width:5%;text-align:center"></th>
<th style="width:10%;text-align:center"">Day</th>
<th style="width:10%;">Date</th>
<th style="width:15%;text-align:center">Reading</th>
<th style="width:50%;">Topic</th>
<th style="width:10%;text-align:center">Materials</th>
</tr>
</thead>


<tbody>

<!-- <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Notes and Script file updated 09-24-2019]*</span></td> -->

<!-- READING <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a> -->

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">1</td>
<td style="vertical-align:middle;">Sept. 05</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Welcome to EPsy 5261</td>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
</tr>


<!-- Unit 01: STATISTICAL COMPUTATION -->

<tr>
<td colspan="5"><b>Unit 01: Statistical Computation</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">2</td>
<td style="vertical-align:middle;">Sept. 07</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Introduction to Coding</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day02.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">3</td>
<td style="vertical-align:middle;">Sept. 12</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/01-01-r-and-rstudio-installation.html">Ch. 1--2</span></a>
</td>
<td>Introduction to R and RStudio</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day03.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>

<!-- Unit 02: SUMMARIZING AND VISUALIZING DATA -->

<tr>
<td colspan="5"><b>Unit 02: Summarizing and Visualizing Data</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">4</td>
<td style="vertical-align:middle;">Sept. 14</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/02-01-data-structure-and-attributes.html">Ch. 4--6</span></a>
</td>
<td>Visualization and Numerical Summaries</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day04.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>

<!-- <tr> -->
<!-- <td></td> -->
<!-- <td style="vertical-align:middle; background-color:#e0bed1;">**Lab Assignment #1 Due**</td> -->
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <a class="my-link" href="files/day04.zip"><span class="fa-solid fa-file-signature"></span></a> -->
<!-- </td> -->
<!-- </tr> -->


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">5</td>
<td style="vertical-align:middle;">Sept. 19</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Visualization and Numerical Summaries</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day05.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<!-- Unit 03: HYPOTHESIS TESTING -->

<tr>
<td colspan="5"><b>Unit 03: Hypothesis Testing</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">6</td>
<td style="vertical-align:middle;">Sept. 21</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/04-01-case-study-teen-sleep.html">Ch. 7--8</span></a>
</td>
<td>Estimating Uncertainty</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day06.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">7</td>
<td style="vertical-align:middle;">Sept. 26</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Introduction to Hypothesis Testing</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day07.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">8</td>
<td style="vertical-align:middle;">Sept. 28</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Simulation-Based Hypothesis Testing</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day08.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">9</td>
<td style="vertical-align:middle;">Oct. 03</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/04-03-one-sample-test.html">Ch. 9--11</span></a>
</td>
<td>Hypothesis Testing with the *t*-distribution</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day09.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">10</td>
<td style="vertical-align:middle;">Oct. 05</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/04-06-one-sample-test-proportions.html">Ch. 12</span></a>
</td>
<td>Hypothesis Testing for Proportions</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day10.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">11</td>
<td style="vertical-align:middle;">Oct. 10</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/05-01-two-sample-t-test.html">Ch. 13--14</span></a>
</td>
<td>Hypothesis Testing for Comparing Two Means</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day11.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">12</td>
<td style="vertical-align:middle;">Oct. 12</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/05-03-two-sample-test-proportions.html">Ch. 15</span></a>
</td>
<td>Hypothesis Testing for Comparing Two Proportions</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day12.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">13</td>
<td style="vertical-align:middle;">Oct. 17</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/06-01-generalization.html">Ch. 17</span></a>
</td>
<td>Study Design: Generalizability</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day13.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">14</td>
<td style="vertical-align:middle;">Oct. 19</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/06-02-cause-and-effect.html">Ch. 18</span></a>
</td>
<td>Study Design: Causal Claims</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day14.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">15</td>
<td style="vertical-align:middle;">Oct. 24</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS---Mental Health Day 🛌 🍷</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


<!-- Unit 04: EFFECT SIZE -->

<tr>
<td colspan="5"><b>Unit 04: Effect Size</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">16</td>
<td style="vertical-align:middle;">Oct. 26</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/07-01-confidence-intervals.html">Ch. 19--21</span></a>
</td>
<td>Introduction to Confidence Intervals</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day16.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">17</td>
<td style="vertical-align:middle;">Oct. 31</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Confidence Intervals for a Single Mean</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day17.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">18</td>
<td style="vertical-align:middle;">Nov. 02</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Confidence Intervals for a Single Proportion</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day18.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">19</td>
<td style="vertical-align:middle;">Nov. 07</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Confidence Intervals for Comparing Two Means</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day19.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">20</td>
<td style="vertical-align:middle;">Nov. 09</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Confidence Intervals for Comparing Two Proportions</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day20.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">21</td>
<td style="vertical-align:middle;">Nov. 14</td>
<td align="center" style="vertical-align:middle;"></td>
<td>More Confidence Intervals</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day21.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">22</td>
<td style="vertical-align:middle;">Nov. 16</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="https://zief0002.github.io/epsy-5261/07-04-standardized-effects-means.html">Ch. 22--23</span></a>
</td>
<td>Standardized Effect Size</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day22.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">23</td>
<td style="vertical-align:middle;">Nov. 21</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS---Mental Health Day 🛌 🍷</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">24</td>
<td style="vertical-align:middle;">Nov. 23</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS---Thanksgiving Break 🦃 🌽 🥧</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


<!-- Unit 05: CORRELATION AND REGRESSION -->

<tr>
<td colspan="5"><b>Unit 05: Correlation and Regression</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">25</td>
<td style="vertical-align:middle;">Nov. 28</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a> -->
</td>
<td>Introduction to Correlation</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day25.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">26</td>
<td style="vertical-align:middle;">Nov. 30</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a> -->
</td>
<td>Introduction to Simple Linear Regression</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day26.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">27</td>
<td style="vertical-align:middle;">Dec. 05</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a> -->
</td>
<td>Simple Linear Regression (Continued)</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day27.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">28</td>
<td style="vertical-align:middle;">Dec. 07</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a> -->
</td>
<td>Simple Linear Regression (Continued)</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day28.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">29</td>
<td style="vertical-align:middle;">Dec. 12</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a> -->
</td>
<td>Review Day</td>
<td align="center" style="vertical-align:middle;">
  <a class="my-link" href="files/day29.zip"><span class="fa-solid fa-folder"></span></a>
</td>
</tr>





</tbody>
</table>    


